### ISSUE TITLE
Google Action Intents getting multiplied for every language

### ISSUE THREAD

**Issue by rubenaeg** [jovotech/jovo-cli#180]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
`jovo build` should create one intent for each defined in the language model.

## Current Behavior
`jovo build` creates duplicated intents, as the required uuid is not being generated.
See https://community.jovo.tech/t/google-action-intents-getting-multiplied-for-every-language/1074.

### Error log
```
If you have an error log, please paste it here.
```

## Your Environment

* Jovo CLI version used: 1.x.x
* Operating System:

**Comment by painbank** [comment]
Actually, I am able to now reproduce the issue of Dialogflow importing the duplicate Intents.  The issue is also due to the utterance objects in the json language files require a new json object calling out the language in them.  IF the intent object doesn't contain the language object, then Dialogflow doesn't know where to put it, even though they should be using the file name, at some point Google made a change to use the JSON object instead of the filename.

here is the new object that needs included for each intent utterance:


`    "lang": "en-ca",`

I have not yet tested where an utterance in one of the files is missing this object and the others have it.  I've only tested where it is present or missing in all the objects.  Here is a full example object, which would be in one of the usersays filenames:

```

  {
    "id": "fbe7f41d-1151-4897-a8c7-34d67945d0cc",
    "data": [
      {
        "text": "to test new abilities",
        "userDefined": false
      }
    ],
    "isTemplate": false,
    "count": 0,
    "lang": "en-ca",
    "updated": 0
  },
```
