### ISSUE TITLE
Only works on node 8+

### ISSUE THREAD

**Issue by tjbenton** [jovotech/jovo-cli#5]
This app only works if you're on node 8 or higher which you can't use when developing Alexa skills since lambda functions can only be at 6.10. 

You might consider compiling you JS with babel to support 6.10 so that users of `jovo-cli` don't have to switch node versions just to use it.

**Comment by jankoenig** [comment]
Thank you @tjbenton, we will look into this. I'm a bit confused, because jovo-cli is mainly used for local development, and the jovo-framework package (which is used for the voice apps) supports earlier node versions, even node 4 (see https://travis-ci.org/jovotech/jovo-framework-nodejs).

Do you mind explaining further? Thanks a lot!

**Comment by tjbenton** [comment]
When I try to install `jovo-cli` in node 4-7 it doesn't work when I try to run it. It only works then I install it on node 8+

![screen shot 2017-11-02 at 11 06 55 am](https://user-images.githubusercontent.com/4776422/32333435-4399d888-bfbe-11e7-8f55-7517d1b1b58e.jpg)

**Comment by jankoenig** [comment]
Thanks! Will investigate.  @aswetlow got it to work with nvm and node 5. Do you have the same issue with other command line tools @tjbenton? for example https://github.com/bespoken/bst

**Comment by tjbenton** [comment]
When I install `bespoken-tools` on any node version it's working correctly for me.

**Comment by jankoenig** [comment]
Thanks! We found the bug and pushed the new version to npm. Can you update it with `npm update -g jovo-cli` and try again?
