### ISSUE TITLE
Environment variables for ask/aws cli tools are ignored when called by jovo

### ISSUE THREAD

**Issue by toto** [jovotech/jovo-cli#85]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

Amazon's AWS and ASK CLI tools allow the use of environment variables as credentials instead of the JSON config files (`~/.ask/cli_config` and `~/.aws/credentials`). The supported variables are described in [Amazon's ASK docs here](https://developer.amazon.com/docs/smapi/manage-credentials-with-ask-cli.html#ask-cli-env-vars) and [for AWS docs here](https://developer.amazon.com/docs/smapi/manage-credentials-with-ask-cli.html#aws-env-vars).

Namely:

- `aws` should use `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` if set, even if launched by jovo CLI
- `ask` should use `ASK_DEFAULT_PROFILE`, `ASK_ACCESS_TOKEN`, `ASK_REFRESH_TOKEN` and `ASK_VENDOR_ID` if set, even if launched by jovo CLI. 

## Current Behavior

The environment variables are ignored even if set. This is very unfortunate for things like CI runners. 

### Error log

Output looks like this:
```
[13:45:09] Deploying Alexa Skill  [started]
[13:45:09] Updating Alexa Skill project for ASK profile default [started]
[13:45:11] Updating Alexa Skill project for ASK profile default [failed]
```

with various errors due to an unconfigured `ask` tool since the env config is ignored.. 

## Your Environment

* Jovo CLI version used: 2.2.2
* Operating System: Docker `node:8` Linux image

**Comment by jankoenig** [comment]
Hi @toto, thanks for pointing this out! We will take a look

**Comment by janober** [comment]
I have good and bad news.

I start with the good:
You can now use the AWS environment variables: `AWS_ACCESS_KEY_ID` & `AWS_SECRET_ACCESS_KEY`

The bad:
I am unable to get the ASK environment variables to work as I and I guess you expected they do. Somehow it seems like "ask" always expects a "cli_config" file. So even if I have all these environment variables set: 
 - ASK_DEFAULT_PROFILE
 - ASK_ACCESS_TOKEN
 - ASK_REFRESH_TOKEN
 - ASK_VENDOR_ID

And I execute: `ask api list-skills`

I get:
`Invalid json: /root/.ask/cli_config`

They actually even write it in the documentation:
`You can use the ASK CLI environment variables in conjunction with or in addition to the ASK CLI configuration file.`

English is not my first language but for me "in conjunction" and "in addition" seems to be kind of the same here?!?! So I first thought it was an error and one of them was meant to say "instead of". But as it turns you not. If you get it working without the file please tell me how. I will then integrate it.

The new version with the fix will be released the next days.

**Comment by toto** [comment]
The AWS vars were actually my bigger concern. I'm mostly tying to deploy a skill in GitLab CI. So I guess my CI skill will keep this line:

```
"echo '{\"profiles\": {\"default\": {\"aws_profile\": \"ask_cli_default\", \"vendor_id\": \"vendor\", \"token\": {...}}}}' > $HOME/.ask/cli_config"
```

**Comment by janober** [comment]
Ah, then you are in luck. 

Yes, I guess something like that has to stay in there. Did honestly not test what exactly has to be in the file and what can be removed.

**Comment by toto** [comment]
I checked but unfortunately it seems you need the whole file structure incl. access/refresh tokens. When they are present they are not used if the env vars are set. This kind of defeats the purpose in some way. I guess I will try to take a look at the `ask-cli` tool. Maybe I can get it fixed on their side.

**Comment by janober** [comment]
Yes, I also do not really understand that. Makes no sense. Anyway hope you find a solution in the ask-cli.
